spring:
  application: name:umc3_teamproject
  datasource:
    url: jdbc:mysql://localhost:3306/TEXTROAD?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  driver-class-name: com.mysql.cj.jdbc.Driver

  #swagger? ?? ???
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



jpa:
  hibernate:
    ddl-auto: create-drop
  properties:
    hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  show_sql: true
  format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug


