spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/umc3?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: kyungmin_root

  #swagger? ?? ???
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show_sql: true
    format_sql: true

logging:
  level:
    org.hibernate.SQL: debug